name: 'Local Intros'
guid: '07d86795-01f2-4d22-b174-cdc6056c3e7c'
version: '2.2.0.0'
targetAbi: '10.8.0.0'
framework: 'net6.0'
owner: 'BrianCArnold'
overview: 'Display flashy intros before movies and other videos'
description: >
  Select a flashy pre-roll from local storage to run before any
  video content. The video details are loaded from disk after a video
  is played from the library from the beginning of the video.
  A random video is selected, and all videos in the local directory
  are enabled by default. Specific videos can be enabled or disabled 
  as necessary. After videos are loaded for the first time, additional
  videos found in the directory are not enabled by default.
category: 'Other'
artifacts:
- 'Jellyfin.Plugin.LocalIntros.dll'
changelog: >
  Disabled Vimeo loading entirely, only plays back local videos.
